const mongoose = require("mongoose");

const EducationSchema = new mongoose.Schema(
  {
    school: { type: String, required: true, trim: true },
    degree: { type: String, required: true, trim: true },
    field: { type: String, required: true, trim: true },
    startYear: { type: String, trim: true },
    endYear: { type: String, trim: true },
  },
  { _id: false }
);

const ExperienceSchema = new mongoose.Schema(
  {
    company: { type: String, required: true, trim: true },
    title: { type: String, required: true, trim: true },
    startDate: { type: String, trim: true },
    endDate: { type: String, trim: true },
    location: { type: String, trim: true },
    // bullets will be generated by AI later
    bullets: [{ type: String, trim: true }],
  },
  { _id: false }
);

const ResumeSchema = new mongoose.Schema(
  {
    fileName: String,
    fileUrl: String,
    uploadedAt: { type: Date, default: Date.now },
    isActive: { type: Boolean, default: true },
  },
  { _id: false }
);

const CandidateSchema = new mongoose.Schema(
  {
    // link to user account (keep this)
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
    },

    // ✅ candidate profile fields (from the form)
    fullName: { type: String, trim: true },
    email: { type: String, trim: true },
    phone: { type: String, trim: true },
    location: { type: String, trim: true },

    targetRole: { type: String, trim: true },
    summary: { type: String, trim: true },

    // ✅ keep skills but store as array
    skills: [{ type: String, trim: true }],

    // ✅ keep experience level (rename so it doesn't clash with work history)
    experienceLevel: {
      type: String,
      enum: ["entry", "mid", "senior", "executive"],
      default: "entry",
    },

    // ✅ real education + work history data
    education: [EducationSchema],
    workHistory: [ExperienceSchema],

    // existing resumes array (keep)
    resumes: [ResumeSchema],

    // recruiter assignment (keep but align naming)
    assignedRecruiterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Candidate", CandidateSchema);
