const mongoose = require("mongoose");

const EducationSchema = new mongoose.Schema(
  {
    school: { type: String, required: true, trim: true },
    degree: { type: String, required: true, trim: true },
    field: { type: String, required: true, trim: true },
    startYear: { type: String, trim: true },
    endYear: { type: String, trim: true },
  },
  { _id: false }
);

const ExperienceSchema = new mongoose.Schema(
  {
    company: { type: String, required: true, trim: true },
    title: { type: String, required: true, trim: true },
    startDate: { type: String, trim: true },
    endDate: { type: String, trim: true },
    location: { type: String, trim: true },
    // bullets will be generated by AI later
    bullets: [{ type: String, trim: true }],
  },
  { _id: false }
);

const ResumeSchema = new mongoose.Schema(
  {
    fileName: { type: String, trim: true },
    fileUrl: { type: String, trim: true },
    uploadedAt: { type: Date, default: Date.now },
    isActive: { type: Boolean, default: true },
  },
  { _id: false }
);

const CandidateSchema = new mongoose.Schema(
  {
    // link to user account (keep this)
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
      index: true,
    },

    // ✅ candidate profile fields (from the form)
    fullName: { type: String, trim: true, index: true },
    email: { type: String, trim: true, lowercase: true, index: true },
    phone: { type: String, trim: true },
    location: { type: String, trim: true },

    targetRole: { type: String, trim: true },
    summary: { type: String, trim: true },

    // ✅ keep skills but store as array
    skills: [{ type: String, trim: true }],

    // ✅ keep experience level (rename so it doesn't clash with work history)
    experienceLevel: {
      type: String,
      enum: ["entry", "mid", "senior", "executive"],
      default: "entry",
    },

    // ✅ Subscription + payment (Admin dashboard depends on these)
    subscriptionPlan: {
      type: String,
      enum: ["free", "silver", "gold", "platinum", "enterprise"],
      default: "free",
      index: true,
    },
    subscriptionStatus: {
      type: String,
      enum: ["active", "inactive"],
      default: "inactive",
      index: true,
    },
    paymentStatus: {
      type: String,
      enum: ["none", "pending", "paid"],
      default: "none",
      index: true,
    },

    // ✅ Credentials (IMPORTANT: NEVER store plaintext password)
    username: { type: String, trim: true, default: "", index: true },
    passwordHash: { type: String, default: "" },
    credentialsGenerated: { type: Date, default: null },
    credentialsUpdatedBy: { type: String, default: "" }, // e.g. "admin" or userId

    // ✅ real education + work history data
    education: [EducationSchema],
    workHistory: [ExperienceSchema],

    // existing resumes array (keep)
    resumes: [ResumeSchema],

    // ✅ recruiter assignment (keep your existing naming but add metadata)
    assignedRecruiterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", // recruiter user account
      default: null,
      index: true,
    },
    recruiterStatus: { type: String, default: "" }, // e.g. "new", "in_progress", "completed"
    assignedDate: { type: Date, default: null },
  },
  { timestamps: true }
);

// Helpful compound index for admin searching/filtering
CandidateSchema.index({ assignedRecruiterId: 1, subscriptionStatus: 1 });
CandidateSchema.index({ subscriptionPlan: 1, paymentStatus: 1 });

module.exports = mongoose.model("Candidate", CandidateSchema);
